name: gitp_llm_project
channels:
  - defaults
  - conda-forge
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - anyio=4.7.0
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.11.4
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.3
  - datasets=3.3.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - dill=0.3.8
  - distro=1.9.0
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - filelock=3.17.0
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gflags=2.2.2
  - glog=0.5.0
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.31.2
  - idna=3.7
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - ipykernel=7.1.0
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jiter=0.6.1
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - libabseil=20250127.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.12.1
  - libevent=2.1.12
  - libffi=3.4.4
  - libgrpc=1.71.0
  - libmpdec=4.0.0
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libthrift=0.15.0
  - lz4-c=1.9.4
  - matplotlib-inline=0.2.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - multidict=6.1.0
  - multiprocess=0.70.15
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openai=1.77.0
  - openpyxl=3.1.5
  - openssl=3.1.0
  - orc=2.1.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.5
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - protobuf=5.29.3
  - psutil=5.9.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pycparser=2.21
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.13
  - pytz=2024.1
  - pywin32=308
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2024.07.02
  - regex=2024.11.6
  - requests=2.32.4
  - safetensors=0.5.3
  - setuptools=72.1.0
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tokenizers=0.21.0
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.51.3
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.14
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.6
prefix: C:\Users\aks284\AppData\Local\miniconda3\envs\gitp_llm_project
