name: gitp_llm_project
channels:
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.4=py313haa95532_0
  - aiohttp=3.11.10=py313h827c3e9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - annotated-types=0.6.0=py313haa95532_0
  - anyio=4.7.0=py313haa95532_0
  - arrow-cpp=19.0.0=h33d5241_2
  - attrs=24.3.0=py313haa95532_0
  - aws-c-auth=0.6.19=h2bbff1b_0
  - aws-c-cal=0.5.20=h2bbff1b_0
  - aws-c-common=0.8.5=h2bbff1b_0
  - aws-c-compression=0.2.16=h2bbff1b_0
  - aws-c-event-stream=0.2.15=hd77b12b_0
  - aws-c-http=0.6.25=h2bbff1b_0
  - aws-c-io=0.13.10=h2bbff1b_0
  - aws-c-mqtt=0.7.13=h2bbff1b_0
  - aws-c-s3=0.1.51=h2bbff1b_0
  - aws-c-sdkutils=0.1.6=h2bbff1b_0
  - aws-checksums=0.1.13=h2bbff1b_0
  - aws-crt-cpp=0.18.16=hd77b12b_0
  - aws-sdk-cpp=1.11.212=h6a15179_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.4.2=py313h2cb717b_0
  - brotlicffi=1.0.9.2=py313h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2025.2.25=haa95532_0
  - certifi=2025.6.15=py313haa95532_0
  - cffi=1.17.1=py313h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py313haa95532_0
  - datasets=3.3.2=py313haa95532_0
  - dill=0.3.8=py313haa95532_0
  - distro=1.9.0=py313haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - filelock=3.17.0=py313haa95532_0
  - frozenlist=1.5.0=py313h827c3e9_0
  - fsspec=2024.12.0=py313haa95532_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - h11=0.16.0=py313haa95532_0
  - httpcore=1.0.9=py313haa95532_0
  - httpx=0.28.1=py313haa95532_0
  - huggingface_hub=0.31.2=py313haa95532_0
  - idna=3.7=py313haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jiter=0.6.1=py313hefb1915_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.12.1=h9da9810_0
  - libevent=2.1.12=h56d1f94_1
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.71.0=hf4237ab_0
  - libmpdec=4.0.0=h827c3e9_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=h4364b78_2
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py313h827c3e9_2
  - mkl_fft=1.3.11=py313h827c3e9_0
  - mkl_random=1.2.8=py313hce38976_0
  - multidict=6.1.0=py313h827c3e9_0
  - multiprocess=0.70.15=py313haa95532_0
  - numexpr=2.10.1=py313h4cd664f_0
  - numpy=2.3.1=py313ha127e54_0
  - numpy-base=2.3.1=py313haaa8b43_0
  - openai=1.77.0=py313haa95532_0
  - openssl=3.0.16=h3f729d1_0
  - orc=2.1.1=hd1c1d5c_0
  - packaging=24.2=py313haa95532_0
  - pandas=2.2.3=py313h5da7b33_0
  - pip=25.1=pyhc872135_2
  - propcache=0.3.1=py313h827c3e9_0
  - protobuf=5.29.3=py313h5da7b33_0
  - pyarrow=19.0.0=py313h5da7b33_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.7=py313haa95532_0
  - pydantic-core=2.33.2=py313h215eeae_0
  - pysocks=1.7.1=py313haa95532_0
  - python=3.13.5=h286a616_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py313h827c3e9_0
  - python_abi=3.13=0_cp313
  - pytz=2024.1=py313haa95532_0
  - pyyaml=6.0.2=py313h827c3e9_0
  - re2=2024.07.02=h214f63a_0
  - regex=2024.11.6=py313h827c3e9_0
  - requests=2.32.4=py313haa95532_0
  - safetensors=0.5.3=py313hbdb9fe4_0
  - setuptools=72.1.0=py313haa95532_0
  - six=1.17.0=py313haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sniffio=1.3.0=py313haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h5e9d12e_1
  - tokenizers=0.21.0=py313hbd09cc8_0
  - tqdm=4.67.1=py313h4442805_0
  - transformers=4.51.3=py313haa95532_0
  - typing-extensions=4.12.2=py313haa95532_0
  - typing-inspection=0.4.0=py313haa95532_0
  - typing_extensions=4.12.2=py313haa95532_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py313haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.42=haa95532_5
  - vs2015_runtime=14.42.34433=hbfb602d_5
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_0
  - xxhash=0.8.0=h2bbff1b_3
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.18.0=py313h827c3e9_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
